version: "3"

services:
  aws-s3-mock:
    image: adobe/s3mock
    ports:
      - 9090:9090
      - 9191:9191
    environment:
      - initialBuckets=test
      - retainFilesOnExit=true
      - debug=true
